Switch out numba for numba-cuda
NVIDIA/numbast pull request #75
Opened 2024-08-28 16:55 UTC by quasiben

Closes #68

2024-08-29 13:57 UTC, quasiben commented
Switching Numba for numba-cuda in various requirement/env files was naively implemented.  Do you think we should also specify `numba>=0.59.0` or is it safe to rely on numba-cuda to depend on the correct Numba version

2024-09-10 02:30 UTC, isVoid commented
> Switching Numba for numba-cuda in various requirement/env files was naively implemented. Do you think we should also specify `numba>=0.59.0` or is it safe to rely on numba-cuda to depend on the correct Numba version

I think we should be safe to depend on `numba-cuda` for the correct numba version. Since it currently [pins on](https://github.com/NVIDIA/numba-cuda/blob/506ec1af0579abc6f39a0296b1aa3a2e11ca528f/pyproject.toml#L21) `>=0.59.1`, which is larger than all current Numbast pinnings.

2024-09-10 03:25 UTC, isVoid requested changes
Should we also update `numbast/pyproject.toml` too? @quasiben

2024-09-11 14:50 UTC, isVoid commented
I saw there are these failures in the tests:
```
      /__w/numbast/numbast/numbast_extensions/curand_host/curand_host_api.cpp:9:10: fatal error: curand.h: No such file or directory
          9 | #include <curand.h>
```

Currently, the curand are just for demo purposes, and we are hand building some of the host APIs necessary to test out the device bindings. These bindings are exported through pybind. The cmake file here:
https://github.com/NVIDIA/numbast/blob/7f36a8c628a06e6cc36d64e7b0c43b99c4dc4f2a/numbast_extensions/curand_host/CMakeLists.txt
does the building. It seems like the CMake has the findpackage command for CTK, but no lines on adding the include directories to the `target_include_directories`, which makes me wonder if we should add
```
target_include_directories(curand_host PUBLIC ${CUDAToolkit_INCLUDE_DIRS})
```
to the cmakelists.txt.

2024-09-19 07:47 UTC, isVoid commented
Further debug shows the failure relates to a known issue that CTK12.3 delivered by conda could cause cmake not resolving to the correct CTK include paths, which is why `curand.h` is not found in the build process. In fact, the issue is known in #53 . I plan to bump the CTK version to 12.5+ to resolve this issue: tracking PR: #77

2024-10-07 07:27 UTC, isVoid approved these changes

2024-10-07 07:27 UTC, merged